openapi: 3.0.3
info:
  title: Database Migration Management API
  description: Management endpoints for Flyway database schema operations
  version: 1.0.0
  contact:
    name: Development Team

servers:
  - url: http://localhost:8080
    description: Development server

paths:
  /api/migrations:
    get:
      summary: Get migration status and history
      description: Retrieve current database schema version and migration history
      operationId: getMigrationStatus
      tags:
        - Migration Management
      responses:
        '200':
          description: Migration status retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MigrationStatus'
              examples:
                success:
                  summary: Successful migration status
                  value:
                    currentVersion: "V3__Add_audit_columns"
                    pendingMigrations: []
                    appliedMigrations:
                      - id: 1
                        version: "V1__Create_initial_tables"
                        description: "Create initial tables"
                        installedOn: "2025-11-03T10:00:00Z"
                        executionTime: 250
                        success: true
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/migrations/validate:
    post:
      summary: Validate pending migrations
      description: Validate checksums and syntax of pending migrations
      operationId: validateMigrations
      tags:
        - Migration Management
      responses:
        '200':
          description: Validation completed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationResult'
        '400':
          description: Validation failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationResult'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/migrations/migrate:
    post:
      summary: Execute pending migrations
      description: Apply all pending database migrations
      operationId: executeMigrations
      tags:
        - Migration Management
      responses:
        '200':
          description: Migrations executed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MigrationResult'
        '409':
          description: Migration conflict or validation failure
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Migration execution failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/migrations/info:
    get:
      summary: Get detailed migration information
      description: Retrieve detailed information about all migrations
      operationId: getMigrationInfo
      tags:
        - Migration Management
      parameters:
        - name: version
          in: query
          description: Specific migration version to retrieve
          required: false
          schema:
            type: string
            pattern: '^V\d+__.*$'
      responses:
        '200':
          description: Migration information retrieved
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MigrationInfo'
        '404':
          description: Migration version not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    MigrationStatus:
      type: object
      properties:
        currentVersion:
          type: string
          description: Current database schema version
          example: "V3__Add_audit_columns"
        pendingMigrations:
          type: array
          items:
            type: string
          description: List of pending migration versions
          example: ["V4__Add_user_indexes"]
        appliedMigrations:
          type: array
          items:
            $ref: '#/components/schemas/AppliedMigration'
        databaseState:
          type: string
          enum: [CLEAN, DIRTY, OUT_OF_ORDER, MISSING_MIGRATIONS]
          description: Overall database state

    AppliedMigration:
      type: object
      properties:
        id:
          type: integer
          description: Migration record ID
          example: 1
        version:
          type: string
          description: Migration version
          example: "V1__Create_initial_tables"
        description:
          type: string
          description: Migration description
          example: "Create initial tables"
        installedOn:
          type: string
          format: date-time
          description: When migration was applied
          example: "2025-11-03T10:00:00Z"
        executionTime:
          type: integer
          description: Execution time in milliseconds
          example: 250
        success:
          type: boolean
          description: Whether migration was successful
          example: true

    MigrationInfo:
      type: object
      properties:
        version:
          type: string
          description: Migration version
          example: "V1__Create_initial_tables"
        description:
          type: string
          description: Migration description
          example: "Create initial tables"
        script:
          type: string
          description: SQL script content preview
          example: "CREATE TABLE employee (...)"
        checksum:
          type: string
          description: MD5 checksum
          example: "a1b2c3d4e5f6..."
        state:
          type: string
          enum: [PENDING, APPLIED, FAILED, OUT_OF_ORDER]
          description: Migration state
        installedOn:
          type: string
          format: date-time
          description: When migration was applied
        executionTime:
          type: integer
          description: Execution time in milliseconds

    ValidationResult:
      type: object
      properties:
        valid:
          type: boolean
          description: Whether validation passed
          example: true
        errors:
          type: array
          items:
            type: string
          description: Validation errors
          example: []
        warnings:
          type: array
          items:
            type: string
          description: Validation warnings
          example: ["Migration V4 takes longer than recommended"]

    MigrationResult:
      type: object
      properties:
        success:
          type: boolean
          description: Whether migrations were successful
          example: true
        migrationsExecuted:
          type: integer
          description: Number of migrations executed
          example: 2
        executionTime:
          type: integer
          description: Total execution time in milliseconds
          example: 1250
        appliedMigrations:
          type: array
          items:
            $ref: '#/components/schemas/AppliedMigration'
        failures:
          type: array
          items:
            $ref: '#/components/schemas/MigrationFailure'
          description: List of failed migrations if any

    MigrationFailure:
      type: object
      properties:
        version:
          type: string
          description: Failed migration version
          example: "V4__Add_user_indexes"
        errorCode:
          type: string
          description: Error code
          example: "SQL_SYNTAX_ERROR"
        errorMessage:
          type: string
          description: Error message
          example: "Syntax error at line 5"
        timestamp:
          type: string
          format: date-time
          description: When failure occurred
          example: "2025-11-03T11:30:00Z"

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: Error type
          example: "VALIDATION_FAILED"
        message:
          type: string
          description: Error message
          example: "Migration validation failed due to checksum mismatch"
        details:
          type: object
          description: Additional error details
          example:
            migration: "V4__Add_user_indexes"
            expectedChecksum: "a1b2c3d4..."
            actualChecksum: "z9y8x7w6..."
        timestamp:
          type: string
          format: date-time
          description: Error timestamp
          example: "2025-11-03T11:30:00Z"

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - BearerAuth: []

tags:
  - name: Migration Management
    description: Database migration and schema management operations